### PR TITLE
Upgrade to OkHttp 3.10 with JDK9+ support

### PR DESCRIPTION
**Pull request by aclowkey**

### CODE REVIEW

**Comment by judepereira** [comment]
See https://github.com/CleverTap/apns-http2/issues/44#issuecomment-397269427.

**Comment by judepereira** [comment]
@aclowkey Can you add in an integration test with a placeholder for the auth key and token? I'll set up these two as encrypted environment parameters in Travis CI - we'll be able to test this out in a better manner.

**Comment by aclowkey** [comment]
I'm not familiar with the API. Do you mean use set up the client in this way:
```java
APN_AUTH_KEY = ; // TODO Where will this come from? 
KEY_ID = ...
asyncClient = new ApnsClientBuilder().
                inAsynchronousMode().
                withApnsAuthKey(APN_AUTH_KEY).
                withKeyID(KEY_ID)
```

**Comment by judepereira** [comment]
It’ll be an environment variable - System.getProperty().

**Pull request closed without merging**
