### PR TITLE
Adding Topic, Upgrade Jetty version

### PR DESCRIPTION
**Pull request by fcioffi**
Would you collaborate on developing?

### CODE REVIEW

**Comment by judepereira** [comment]
Absolutely @fcioffi.
Could you declare the overloaded push() with topic for the synchronous one in the interface?
I see that the following is missing in the interface:
```
public NotificationResponse push(String topic, Notification notification);
```

**Comment by fcioffi** [comment]
It's right! Can you check now?

**Comment by judepereira** [comment]
Thanks a lot @fcioffi :)
I'll remove the Test class that you've added. I'll be added JUnit test cases shortly.

**Comment by fcioffi** [comment]
I added on my fork and modified shutdown()

Can you see that?

2016-01-29 14:52 GMT+01:00 Jude Pereira <notifications@github.com>:

> Thanks a lot @fcioffi <https://github.com/fcioffi> :)
> I'll remove the Test class that you've added. I'll be added JUnit test
> cases shortly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CleverTap/apns-http2/pull/1#issuecomment-176763215>.
>



-- 
Francesco Cioffi
Computer engineer
http://www.fcioffi.net

**Comment by judepereira** [comment]
I had a pending commit there. Take a look at my implementation (just pushed). There's a todo there to maintain a shutting down flag and then throw an IllegalArgumentException for any further calls to push(): 
https://github.com/CleverTap/apns-http2/commit/ba993ea2d2a5348ffadcfde5b178204f3059ce0a

**Pull request merged**
