### PR TITLE
New constructors in SyncOkHttpApnsClient to allow customizing the OkHttp clients

### PR DESCRIPTION
**Pull request by upachler**
* Added two new constructors that take a OkHttpClient.Builder instance,
  which allow for custom configured HTTP clients
* Renamed 'getBuilder()' method to 'createDefaultBuilder()' and made it
  public, so it can serve as starting point for new builders that
  are then customized and passed to the new constructors
Note that these changes could also be made to AsyncOkHttpApnsClient in a similar fashion to allow customizing that as well.

### CODE REVIEW

**Comment by judepereira** [comment]
@upachler Could you make createDefaultBuilder() private and use it in ApnsClientBuilder? The API remains clean this way.

The OkHttpClient builder instance can be passed on via the ApnsClientBuilder, and if null, create the default one by calling createDefaultBuilder().

**Comment by upachler** [comment]
I agree, including this into the ApnsClientBuilder is certainly a good idea. But it will require to also add constructors to AsyncOkHttpApnsClient that take the builder instances. Then it'd be quite easy to add a withOkHttpClientBuilder() method that's supported on both sync and async implementations.

However, by making createDefaultBuilder private again you'll lose the ability to get a pre-inizialized OkHttpClient Builder - you'd have to make all the decisions yourself and cannot rely on tested defaults that come from http2-apns.
But I do see that in its current form the change is very SyncOkHttpApnsClient-centric, making an implementation of ApnsClient public.

What do you think about moving and renaming createDefaultBuilder() to ApnsClientBuilder.createDefaultOkHttpClientBuilder()? This way, you can rely on the defaults and customize what you need.

**Comment by judepereira** [comment]
Yes, you can make ApnsClientBuilder#createDefaultOkHttpClientBuilder() public. This works :)

**Comment by upachler** [comment]
It is done. :)

**Comment by judepereira** [comment]
Thanks @upachler!

**Pull request merged**
